### ISSUE TITLE
Questions about Compositionality

### ISSUE THREAD

**Issue by pengzhansun** [cvlab-columbia/expert#9]
An interesting paper. I'm exactly interested in the compositionality mentioned in your paper, but I cannot find codes or related data split in composition. Is it available to share this part?

**Comment by surisdi** [comment]
Hi,

The code is general, you just need to call it with different parameters, for the different experiments. If you look at [scripts/test_lm.sh](https://github.com/cvlab-columbia/expert/blob/master/scripts/test_lm.sh), for example, you will see the following comment:

```
Modify the test_masking_policy to "seen_verbs" (if testing seen verbs), 
"seen_nouns" (if testing seen nouns), "new_combo_seen_noun_seen_verb_merge" 
(if testing new compositions) or "seen_combo_seen_noun_seen_verb_merge" 
(if testing seen compositions).
```

The parameter `test_masking_policy` ends up affecting the way the masks  are created (this is, which words are evaluated), in the function [compute_item_mask](https://github.com/cvlab-columbia/expert/blob/03774757a07f2afd942b3b8f4b1d1676b70b2bba/masker.py#L209).
